# Decision Tree Regression

Importing Library to access dataset

In [1]:
import pandas as pd

Importing dataset

In [2]:
dataset = pd.read_csv("Datasets/T09_Data.csv")

Checking is there any missing value in the dataset

In [3]:
print(dataset.isnull().sum())

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64


Reading X_features and y_outcome

In [4]:
X_features = dataset.iloc[:,:-1].values
y_outcome = dataset.iloc[:, [-1]].values

Printing some data of the X_features and y_outcome

In [5]:
print("X_features ->\n", X_features[:5, :])
print("y_outcome ->\n", y_outcome[:5, :])

X_features ->
 [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]]
y_outcome ->
 [[463.26]
 [444.37]
 [488.56]
 [446.48]
 [473.9 ]]


Checking type of X_features and y_outcome

In [6]:
print("X_features -->", type(X_features))
print("y_outcome -->", type(y_outcome))

X_features --> <class 'numpy.ndarray'>
y_outcome --> <class 'numpy.ndarray'>


# Splitting the dataset into training set and test set

Importing train_test_split model

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X_features, y_outcome, test_size=0.2, random_state=0)

Printing some data of X_train, X_test, y_train, y_test

In [8]:
print("X_train -->\n", X_train[:10, :])
print("X_test --> \n", X_test[:10, :])
print("y_train --> \n", y_train[:10, :])
print("y_test -->\n", y_test[:10, :])

X_train -->
 [[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 [  31.91   67.83 1008.76   53.22]
 [  10.37   37.5  1013.19   79.25]
 [  12.16   40.81 1025.79   70.97]
 [  16.13   39.99 1007.04   80.49]
 [  12.75   42.34 1018.17   94.67]
 [  11.62   41.54 1019.94   66.43]
 [  26.17   48.92 1009.87   34.43]]
X_test --> 
 [[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 [  22.46   58.33 1013.21   68.68]
 [  18.38   55.28 1020.22   68.33]
 [  30.89   74.87 1008.99   56.58]
 [  11.74   43.56 1015.14   70.72]
 [  18.97   50.59 1016.01   74.9 ]
 [  11.42   41.54 1020.21   71.57]
 [  23.89   50.16 1004.88   73.94]]
y_train --> 
 [[473.93]
 [467.87]
 [431.97]
 [425.28]
 [473.1 ]
 [476.63]
 [465.25]
 [465.44]
 [477.75]
 [440.09]]
y_test -->
 [[431.23]
 [460.01]
 [461.14]
 [445.9 ]
 [451.29]
 [432.68]
 [477.5 ]
 [459.68]
 [477.5 ]
 [444.99]]


# Training The Decision Tree Regression Model on The Training Set

##### Here needs, no feature scalling.

Importing the Decision Tree model

In [9]:
from sklearn.tree import DecisionTreeRegressor

Making the instance of Decision Tree

In [10]:
decisionTree = DecisionTreeRegressor(random_state=0)

Fitting the Decision Tree On Training Set

In [11]:
decisionTree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

# Predicting The Test Set Results

In [12]:
y_pred = decisionTree.predict(X_test)

Making the precision of Predicted value to 2

In [13]:
import numpy as np
np.set_printoptions(precision=2)

Printing the predicted value and the test value in two column so we can compare the values

In [14]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)[:10,:])

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 [452.71 445.9 ]
 [459.61 451.29]
 [434.3  432.68]
 [467.83 477.5 ]
 [458.64 459.68]
 [476.89 477.5 ]
 [435.49 444.99]]


# Evaluating The Model Performance

Importing r2_score error model to know the goodness of our model

In [15]:
from sklearn.metrics import r2_score as r

Calculating the accuracy of our model

In [16]:
accuracy = r(y_test, y_pred)

In [18]:
print(accuracy)  # means 92.20% our model is accurate, which is little less accurate than the SVR model we saw.

0.922905874177941
